"""empty message

Revision ID: 0ac63fdcdba9
Revises: 79438396d697
Create Date: 2023-10-04 17:25:19.316081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac63fdcdba9'
down_revision = '79438396d697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
    sa.Column('index', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('index', name='pk_user_history')
    )
    # ### end Alembic commands ###
