"""empty message

Revision ID: 4d1dc89dadb9
Revises: b8a3e8ac16ef
Create Date: 2023-09-07 15:29:05.741865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1dc89dadb9'
down_revision = 'b8a3e8ac16ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.drop_column('modified_date')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('modified_date')

    # ### end Alembic commands ###
