"""empty message

Revision ID: 79438396d697
Revises: 806b4eaeb3d4
Create Date: 2023-09-27 19:25:35.650027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79438396d697'
down_revision = '806b4eaeb3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name=op.f('fk_rating_answer_id_answer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_rating_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rating'))
    )
    op.drop_table('answer_voter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_voter',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('answer_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name='fk_answer_voter_answer_id_answer', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_answer_voter_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'answer_id', name='pk_answer_voter')
    )
    op.drop_table('rating')
    # ### end Alembic commands ###
