"""empty message

Revision ID: 806b4eaeb3d4
Revises: 69abdad58254
Create Date: 2023-09-27 17:00:13.861473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806b4eaeb3d4'
down_revision = '69abdad58254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('index', name=op.f('pk_user_history'))
    )
    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.drop_column('rating')

    op.drop_table('user_history')
    # ### end Alembic commands ###
